import { useCallback, useEffect, useMemo } from 'react';
import { useSettings } from './useSettings';
import { formatCurrencyValue } from '../lib/currency';

export type StorefrontLanguage = 'pt-BR' | 'en-US';

type TranslationMap = Record<string, string>;

const storefrontTranslations: Record<StorefrontLanguage, TranslationMap> = {
  'pt-BR': {
    supportCenterPretitle: 'Central de',
    supportCenterTitle: 'Atendimento',
    supportWhatsappTitle: 'Estamos no whatsapp',
    supportSalesLabel: 'Vendas',
    supportSacLabel: 'SAC',
    supportMessageTitle: 'Envie uma mensagem',
    supportHoursTitle: 'Horario de atendimento',
    supportSendMessage: 'Enviar mensagem',
    welcome: 'Bem-vindo(a)',
    loginOrRegister: 'Entrar ou Cadastrar',
    allCategories: 'Todas as Categorias',
    noAdditionalCategories: 'Nenhuma categoria adicional.',
    menuLaunches: 'Lancamentos',
    menuBestSellers: 'Mais Vendidos',
    menuRaffles: 'Sorteios',
    searchPlaceholder: 'O que voce esta procurando?',
    searchButton: 'Buscar',
    mobileSearchPlaceholder: 'Buscar produto...',
    myAccount: 'Minha Conta',
    favorites: 'Favoritos',
    rafflesAndLoyalty: 'Sorteios e Fidelidade',
    newsletterTitle: 'Cadastre-se e ganhe 10% de desconto',
    newsletterSubtitle: 'Cadastre seu e-mail e ganhe 10% de desconto para primeira compra.',
    newsletterEmailPlaceholder: 'Digite seu email',
    subscribe: 'Assinar',
    aboutStore: 'Sobre a loja',
    content: 'Conteudo',
    contact: 'Contato',
    social: 'Social',
    aboutUs: 'Quem somos',
    contactUs: 'Fale Conosco',
    privacyPolicy: 'Politica de privacidade',
    exchangesPolicy: 'Politica de Trocas e Devolucoes',
    shippingPolicy: 'Politica de frete e pagamento',
    allRightsReserved: 'Todos os direitos reservados.',
    whatsappFloatingLabel: 'Falar no WhatsApp',
    whatsappFloatingMessage: 'Ola, Gostaria de adquirir alguns de seus produtos.',
    contactModalTitle: 'Fale Conosco',
    contactModalSubtitle: 'Preencha o formulario abaixo.',
    contactName: 'Nome',
    contactEmail: 'E-mail',
    contactPhone: 'Telefone',
    contactOrderNumber: 'No do pedido',
    contactMessage: 'Mensagem',
    contactNotRobot: 'Nao sou um robo',
    contactSuccess: 'Mensagem enviada com sucesso!',
    close: 'Fechar',
    send: 'Enviar',
    parcelingTitle: 'Parcelamento',
    parcelingSubtitle: 'Em ate 12x no Cartao',
    cashPaymentTitle: 'Pagamento a Vista',
    cashPaymentSubtitle: '5% de desconto Pix/Boleto',
    securityTitle: 'Seguranca',
    securitySubtitle: 'Loja com SSL de Protecao',
    checkOut: 'Confira',
    activeRaffle: 'Sorteio ativo',
    loyaltyClub: 'Clube de Sorteios',
    raffleDrawOn: 'Sorteio em {date}',
    pointsPerTicket: '{count} pontos por bilhete',
    participateNow: 'Participar agora',
    viewAll: 'Ver todos',
    productNew: 'Novo',
    productSale: 'Sale',
    installments4: 'ate 4x de {value} sem juros',
    viewDetails: 'Ver Detalhes',
    searchResultsFor: 'Resultados para "{query}"',
    launches: 'Lancamentos',
    bestSellers: 'Mais Vendidos',
    promotions: 'Promocoes',
    allProducts: 'Todos os Produtos',
    productsFound: '{count} produtos encontrados',
    filters: 'Filtros',
    sortBy: 'Ordenar por',
    sortDefault: 'Ordenar por: Padrao',
    lowestPrice: 'Menor Preco',
    highestPrice: 'Maior Preco',
    categories: 'Categorias',
    all: 'Todos',
    noProductsFound: 'Nenhum produto encontrado com os filtros selecionados.',
    unableToLoadSection: 'Nao foi possivel carregar esta secao agora.',
    unableToLoadProducts: 'Nao foi possivel carregar os produtos agora.',
    unableToLoadRaffles: 'Nao foi possivel carregar os sorteios agora.',
    unableToLoadCategories: 'Nao foi possivel carregar as categorias agora.',
    tryAgain: 'Tentar novamente',
    clearFilters: 'Limpar filtros',
    productNotFound: 'Produto nao encontrado',
    backToStore: 'Voltar para a loja',
    home: 'Home',
    lastUnits: 'Ultimas {count} pecas disponiveis!',
    installments6: 'ou em ate 6x de {value} sem juros',
    reviewsCount: '({count} avaliacoes)',
    loyaltyBonus: 'Bonus de Fidelidade',
    loyaltyProductCopy: 'Compre e ganhe {points} pontos para o clube de sorteios.',
    color: 'Cor',
    select: 'Selecione',
    size: 'Tamanho',
    sizeGuide: 'Guia de Medidas',
    selectSizeError: 'Por favor, selecione um tamanho.',
    selectColorError: 'Por favor, selecione uma cor.',
    addToCart: 'Adicionar ao Carrinho',
    buyViaWhatsapp: 'Comprar via WhatsApp',
    description: 'Descricao',
    compositionAndDetails: 'Composicao & Detalhes',
    madeInBrazil: 'Feito no Brasil',
    handWashRecommended: 'Lavar a mao recomendado',
    customerReviews: 'Avaliacoes Clientes',
    youMayAlsoLike: 'Voce tambem pode gostar',
    emptyCartTitle: 'Sua sacola esta vazia',
    emptyCartSubtitle: 'Parece que voce ainda nao adicionou nenhum produto a sua sacola de compras.',
    continueShopping: 'Continuar Comprando',
    shoppingBag: 'Sua Sacola',
    product: 'Produto',
    price: 'Preco',
    quantityShort: 'Qtd',
    total: 'Total',
    colorLabel: 'Cor',
    sizeLabel: 'Tamanho',
    remove: 'Remover',
    orderSummary: 'Resumo do Pedido',
    subtotal: 'Subtotal',
    discount: 'Desconto',
    shipping: 'Frete',
    freeShipping: 'Gratis',
    toCalculate: 'A calcular',
    simulateShipping: 'Simular Frete',
    calc: 'Calc',
    freeShippingReached: 'Voce atingiu o frete gratis!',
    discountCoupon: 'Cupom de Desconto',
    code: 'Codigo',
    apply: 'Aplicar',
    finishPurchase: 'Finalizar Compra',
    orContinueShopping: 'Ou continuar comprando',
    couponApplied: 'Cupom aplicado com sucesso.',
    invalidCoupon: 'Cupom invalido.',
    savedShippingAddress: 'Endereco salvo',
    shippingUsingSavedAddress: 'Usando o endereco salvo da sua conta para calcular o frete.',
    guestShippingAddress: 'Endereco para frete',
    signInForSavedAddress: 'Entre na sua conta para usar um endereco salvo e agilizar o checkout.',
    shippingAddressEmpty: 'Voce ainda nao possui um endereco salvo.',
    wishlistEmptyTitle: 'Sua lista de desejos esta vazia',
    wishlistEmptySubtitle: 'Salve seus itens favoritos para compra-los mais tarde. Clique no coracao em qualquer produto para adiciona-lo.',
    exploreProducts: 'Explorar Produtos',
    myFavorites: 'Meus Favoritos',
    itemsCount: '{count} itens',
    removeFromFavorites: 'Remover dos favoritos',
    loyaltyClubTitle: 'Clube de Lealdade',
    rafflesHeroTitle: 'Troque seus pontos por sorte.',
    rafflesHeroSubtitle: 'Cada compra gera pontos. Acumule e troque por bilhetes para nossos sorteios exclusivos.',
    currentBalance: 'Seu Saldo Atual',
    accumulatedPoints: 'Pontos Acumulados',
    activeRafflesTitle: 'Sorteios Ativos',
    drawSoon: 'Em breve',
    participateConfirmed: 'Participacao confirmada! Boa sorte!',
    insufficientPoints: 'Saldo de pontos insuficiente!',
    insufficientPointsButton: 'Pontos Insuficientes',
    noActiveRaffles: 'Nenhum sorteio ativo no momento.',
    howItWorks: 'Como funciona?',
    raffleStepBuy: 'Compre',
    raffleStepBuyDesc: 'Cada compra na loja gera pontos de lealdade conforme o valor gasto.',
    raffleStepAccumulate: 'Acumule',
    raffleStepAccumulateDesc: 'Seus pontos ficam salvos na sua conta.',
    raffleStepJoin: 'Participe',
    raffleStepJoinDesc: 'Troque seus pontos acumulados por bilhetes.',
    yourTickets: 'Seus Bilhetes',
    confirmed: 'Confirmado',
    noTicketsYet: 'Voce ainda nao possui bilhetes para sorteios ativos.',
    accountTitle: 'Minha Conta',
    alreadyCustomer: 'Ja sou cliente',
    password: 'Senha',
    forgotPassword: 'Esqueceu a senha?',
    login: 'Entrar',
    or: 'ou',
    noAccountYet: 'Ainda nao tem conta?',
    noAccountSubtitle: 'Cadastre-se para comprar mais rapido, acompanhar seus pedidos e criar sua lista de desejos.',
    createAccount: 'Criar Conta',
    hello: 'Ola,',
    invalidLoginCredentials: 'E-mail ou senha invalidos.',
    myOrders: 'Meus Pedidos',
    myAddresses: 'Meus Enderecos',
    myData: 'Meus Dados',
    logout: 'Sair',
    loyaltyPointsBalance: 'Voce tem {points} pontos acumulados.',
    viewRaffles: 'Ver Sorteios',
    noOrdersYet: 'Voce ainda nao tem pedidos',
    whatAboutNews: 'Que tal conhecer nossas novidades?',
    seeProducts: 'Ver Produtos',
    primary: 'Principal',
    homeAddress: 'Casa',
    edit: 'Editar',
    addAddress: 'Adicionar Endereco',
    fullName: 'Nome Completo',
    cpf: 'CPF',
    cellphone: 'Celular',
    phoneCountry: 'Pais do telefone',
    birthDate: 'Data de Nascimento',
    birthDateInvalid: 'Informe uma data de nascimento valida no formato DD/MM/AAAA.',
    gender: 'Genero',
    female: 'Feminino',
    male: 'Masculino',
    otherOrNoAnswer: 'Outro / Prefiro nao informar',
    changePassword: 'Alterar Senha',
    saveData: 'Salvar Dados',
    addressModalTitle: 'Adicionar Endereco',
    addressNickname: 'Nome do Endereco (ex: Casa, Trabalho)',
    zipcode: 'CEP',
    street: 'Logradouro',
    number: 'Numero',
    complement: 'Complemento',
    neighborhood: 'Bairro',
    city: 'Cidade',
    state: 'Estado',
    saveAddress: 'Salvar Endereco',
    editMyData: 'Editar Meus Dados',
    saveEdition: 'Salvar Edicao',
    currentPassword: 'Senha Atual',
    yourCurrentPassword: 'Sua senha atual',
    newPassword: 'Nova Senha',
    minimumEightChars: 'No minimo 8 caracteres',
    confirmNewPassword: 'Confirmar Nova Senha',
    repeatNewPassword: 'Repita a nova senha',
    updatePassword: 'Atualizar Senha',
    identification: 'Identificacao',
    identificationSubtitle: 'Faca o seu login ou crie uma conta caso ainda nao possua cadastro',
    accessData: 'Dados para Acesso',
    enterYourEmail: 'Digite o seu email',
    confirmEmail: 'Confirmar e-mail',
    emailConfirmationMismatch: 'Os e-mails informados nao conferem.',
    createPassword: 'Crie uma senha',
    confirmPassword: 'Confirmar senha',
    passwordConfirmationMismatch: 'As senhas informadas nao conferem.',
    accountAlreadyExists: 'Ja existe uma conta cadastrada com este e-mail.',
    accountCreationError: 'Nao foi possivel concluir o cadastro agora.',
    registrationType: 'Tipo de Cadastro',
    individualPerson: 'Pessoa Fisica',
    legalEntity: 'Pessoa Juridica',
    businessRegistrationUnavailable: 'Cadastro empresarial indisponivel no momento.',
    usOnlyRegistrationHint: 'Cadastro disponivel apenas para clientes nos Estados Unidos.',
    usOnlyShippingHint: 'Envios disponiveis apenas para enderecos nos Estados Unidos.',
    personalData: 'Dados Pessoais',
    landline: 'Telefone fixo',
    corporateName: 'Razao Social',
    stateRegistration: 'Inscricao Estadual',
    address: 'Endereco',
    country: 'Pais',
    postalCode: 'Codigo postal',
    stateProvince: 'Estado / Provincia / Regiao',
    dontKnowZipcode: 'Nao sei meu cep',
    addressFieldsLockedHint: 'Digite um CEP valido para liberar os campos de endereco.',
    postalFieldsLockedHint: 'Digite um codigo postal valido para liberar os campos de endereco.',
    addressManualCountryHint: 'Preencha o endereco manualmente para este pais.',
    zipcodeLookupLoading: 'Buscando CEP...',
    zipcodeLookupSuccess: 'CEP encontrado. Complete o numero e os detalhes do endereco.',
    zipcodeLookupNotFound: 'CEP nao encontrado. Preencha o endereco manualmente.',
    zipcodeLookupError: 'Nao foi possivel buscar o CEP agora. Preencha o endereco manualmente.',
    postalLookupLoading: 'Buscando codigo postal...',
    postalLookupSuccess: 'Codigo postal encontrado. Revise os dados e complete o restante do endereco.',
    postalLookupNotFound: 'Codigo postal nao encontrado. Preencha o endereco manualmente.',
    postalLookupError: 'Nao foi possivel buscar o codigo postal agora. Preencha o endereco manualmente.',
    reference: 'Referencia',
    selectOption: 'Selecione',
    cancel: 'Cancelar',
    checkoutConfirmed: 'Pedido Confirmado!',
    thanksForPurchase: 'Obrigado por comprar na {store}.',
    orderNumberCopy: 'O numero do seu pedido e {orderNumber}. Enviaremos as atualizacoes para o seu e-mail.',
    backHome: 'Voltar para Home',
    checkoutStepIdentification: 'Identificacao',
    checkoutStepDelivery: 'Entrega',
    checkoutStepPayment: 'Pagamento',
    personalDataTitle: 'Dados Pessoais',
    goToDelivery: 'Ir para Entrega',
    deliveryAddressTitle: 'Endereco de Entrega',
    avenue: 'Rua / Avenida',
    shippingOptions: 'Opcoes de Frete',
    shippingRatesLoading: 'Buscando opcoes de frete...',
    shippingRatesEstimated: 'Mostrando opcoes estimadas de frete. Conecte um provider como Shippo para tarifas ao vivo.',
    shippingRatesLive: 'Tarifas ao vivo carregadas.',
    shippingRatesError: 'Nao foi possivel carregar as opcoes de frete agora.',
    shippingRatesEmpty: 'Nenhuma opcao de frete disponivel para este destino.',
    shippingMethodRequired: 'Selecione uma opcao de frete para continuar.',
    shippingDeliveryWindow: 'Entrega estimada entre {min} e {max} dias uteis',
    shippingRefresh: 'Atualizar frete',
    businessDays7: 'Ate 7 dias uteis',
    businessDays3: 'Ate 3 dias uteis',
    back: 'Voltar',
    goToPayment: 'Ir para Pagamento',
    paymentTitle: 'Pagamento',
    creditCard: 'Cartao de Credito',
    stripeApplePay: 'Apple Pay',
    stripeGooglePay: 'Google Pay',
    stripeSecureCheckout: 'Checkout Seguro',
    stripeCheckoutTitle: 'Finalize seu pagamento com Stripe',
    stripeCheckoutSubtitle: 'Voce sera redirecionado(a) para um ambiente hospedado e protegido para concluir o pedido com seguranca.',
    stripeCheckoutDisabled: 'A integracao Stripe ainda nao esta ativa no painel administrativo. Ative as chaves para liberar este fluxo.',
    stripeHostedCheckoutHint: 'Checkout hospedado pela Stripe com validacao de pagamento em tempo real.',
    stripeAvailableMethods: 'Meios de pagamento disponiveis',
    stripeNoMethodEnabled: 'Nenhum metodo Stripe habilitado no momento.',
    stripeProtectedPayment: 'Pagamento protegido',
    stripeProtectedPaymentCopy: 'Dados sensiveis do pagamento ficam na Stripe e nao trafegam pela loja.',
    stripeRewardsOnApproval: '{points} pontos liberados apos a aprovacao',
    stripeContinueToCheckout: 'Continuar para o checkout',
    stripeRedirecting: 'Redirecionando...',
    stripeCheckoutError: 'Nao foi possivel iniciar o checkout Stripe agora.',
    stripeVerificationError: 'Nao foi possivel confirmar o pagamento Stripe agora.',
    stripePaymentNotConfirmed: 'O pagamento ainda nao foi confirmado pela Stripe.',
    stripeCheckoutProcessingTitle: 'Confirmando seu pagamento',
    stripeCheckoutProcessingSubtitle: 'Estamos validando a sessao Stripe e finalizando o pedido.',
    stripeCheckoutReturnErrorTitle: 'Nao conseguimos confirmar o pagamento',
    paymentReturnToCart: 'Voltar para o carrinho',
    cardNumber: 'Numero do Cartao',
    cardHolder: 'Nome do Titular',
    validity: 'Validade (MM/AA)',
    installments: 'Parcelamento',
    pixDiscount: 'PIX (5% de Desconto)',
    completeOrder: 'Finalizar Pedido',
    purchaseSummary: 'Resumo da Compra',
    institutionalAbout: 'Sobre a Marca',
    institutionalContact: 'Contato',
    institutionalTerms: 'Termos de Uso',
    institutionalPrivacy: 'Politica de Privacidade',
    institutionalExchanges: 'Trocas e Devolucoes',
    institutionalFaq: 'Perguntas Frequentes',
    institutionalShipping: 'Prazos e Envios',
  },
  'en-US': {
    supportCenterPretitle: 'Support',
    supportCenterTitle: 'Center',
    supportWhatsappTitle: 'We are on WhatsApp',
    supportSalesLabel: 'Sales',
    supportSacLabel: 'Support',
    supportMessageTitle: 'Send a message',
    supportHoursTitle: 'Support hours',
    supportSendMessage: 'Send message',
    welcome: 'Welcome',
    loginOrRegister: 'Sign in or Register',
    allCategories: 'All Categories',
    noAdditionalCategories: 'No additional categories.',
    menuLaunches: 'New Arrivals',
    menuBestSellers: 'Best Sellers',
    menuRaffles: 'Raffles',
    searchPlaceholder: 'What are you looking for?',
    searchButton: 'Search',
    mobileSearchPlaceholder: 'Search product...',
    myAccount: 'My Account',
    favorites: 'Wishlist',
    rafflesAndLoyalty: 'Raffles & Loyalty',
    newsletterTitle: 'Sign up and get 10% off',
    newsletterSubtitle: 'Enter your email and get 10% off your first purchase.',
    newsletterEmailPlaceholder: 'Enter your email',
    subscribe: 'Subscribe',
    aboutStore: 'About the store',
    content: 'Content',
    contact: 'Contact',
    social: 'Social',
    aboutUs: 'About us',
    contactUs: 'Contact us',
    privacyPolicy: 'Privacy policy',
    exchangesPolicy: 'Exchanges & returns policy',
    shippingPolicy: 'Shipping & payment policy',
    allRightsReserved: 'All rights reserved.',
    whatsappFloatingLabel: 'Chat on WhatsApp',
    whatsappFloatingMessage: 'Hello, I would like to purchase some of your products.',
    contactModalTitle: 'Contact Us',
    contactModalSubtitle: 'Fill out the form below.',
    contactName: 'Name',
    contactEmail: 'Email',
    contactPhone: 'Phone',
    contactOrderNumber: 'Order no.',
    contactMessage: 'Message',
    contactNotRobot: 'I am not a robot',
    contactSuccess: 'Message sent successfully!',
    close: 'Close',
    send: 'Send',
    parcelingTitle: 'Installments',
    parcelingSubtitle: 'Up to 12x on credit card',
    cashPaymentTitle: 'Cash payment',
    cashPaymentSubtitle: '5% off with Pix/Boleto',
    securityTitle: 'Security',
    securitySubtitle: 'Store protected with SSL',
    checkOut: 'Check it out',
    activeRaffle: 'Active raffle',
    loyaltyClub: 'Raffle Club',
    raffleDrawOn: 'Draw on {date}',
    pointsPerTicket: '{count} points per ticket',
    participateNow: 'Join now',
    viewAll: 'View all',
    productNew: 'New',
    productSale: 'Sale',
    installments4: 'up to 4x of {value} interest-free',
    viewDetails: 'View details',
    searchResultsFor: 'Results for "{query}"',
    launches: 'New Arrivals',
    bestSellers: 'Best Sellers',
    promotions: 'Promotions',
    allProducts: 'All Products',
    productsFound: '{count} products found',
    filters: 'Filters',
    sortBy: 'Sort by',
    sortDefault: 'Sort by: Default',
    lowestPrice: 'Lowest price',
    highestPrice: 'Highest price',
    categories: 'Categories',
    all: 'All',
    noProductsFound: 'No products found with the selected filters.',
    unableToLoadSection: 'We could not load this section right now.',
    unableToLoadProducts: 'We could not load the products right now.',
    unableToLoadRaffles: 'We could not load the raffles right now.',
    unableToLoadCategories: 'We could not load the categories right now.',
    tryAgain: 'Try again',
    clearFilters: 'Clear filters',
    productNotFound: 'Product not found',
    backToStore: 'Back to store',
    home: 'Home',
    lastUnits: 'Last {count} items available!',
    installments6: 'or up to 6x of {value} interest-free',
    reviewsCount: '({count} reviews)',
    loyaltyBonus: 'Loyalty Bonus',
    loyaltyProductCopy: 'Buy and earn {points} points for the raffle club.',
    color: 'Color',
    select: 'Select',
    size: 'Size',
    sizeGuide: 'Size Guide',
    selectSizeError: 'Please select a size.',
    selectColorError: 'Please select a color.',
    addToCart: 'Add to Cart',
    buyViaWhatsapp: 'Buy via WhatsApp',
    description: 'Description',
    compositionAndDetails: 'Composition & Details',
    madeInBrazil: 'Made in Brazil',
    handWashRecommended: 'Hand wash recommended',
    customerReviews: 'Customer Reviews',
    youMayAlsoLike: 'You may also like',
    emptyCartTitle: 'Your bag is empty',
    emptyCartSubtitle: 'Looks like you have not added any products to your shopping bag yet.',
    continueShopping: 'Continue Shopping',
    shoppingBag: 'Your Bag',
    product: 'Product',
    price: 'Price',
    quantityShort: 'Qty',
    total: 'Total',
    colorLabel: 'Color',
    sizeLabel: 'Size',
    remove: 'Remove',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    discount: 'Discount',
    shipping: 'Shipping',
    freeShipping: 'Free',
    toCalculate: 'To be calculated',
    simulateShipping: 'Calculate Shipping',
    calc: 'Calc',
    freeShippingReached: 'You unlocked free shipping!',
    discountCoupon: 'Discount Coupon',
    code: 'Code',
    apply: 'Apply',
    finishPurchase: 'Proceed to Checkout',
    orContinueShopping: 'Or continue shopping',
    couponApplied: 'Coupon applied successfully.',
    invalidCoupon: 'Invalid coupon.',
    savedShippingAddress: 'Saved address',
    shippingUsingSavedAddress: 'Using your saved account address to calculate shipping.',
    guestShippingAddress: 'Shipping address',
    signInForSavedAddress: 'Sign in to use a saved address and speed up checkout.',
    shippingAddressEmpty: 'You do not have a saved address yet.',
    wishlistEmptyTitle: 'Your wishlist is empty',
    wishlistEmptySubtitle: 'Save your favorite items to buy them later. Click the heart on any product to add it.',
    exploreProducts: 'Explore Products',
    myFavorites: 'My Wishlist',
    itemsCount: '{count} items',
    removeFromFavorites: 'Remove from wishlist',
    loyaltyClubTitle: 'Loyalty Club',
    rafflesHeroTitle: 'Trade your points for luck.',
    rafflesHeroSubtitle: 'Every purchase earns loyalty points. Save up and exchange them for tickets in our exclusive raffles.',
    currentBalance: 'Your Current Balance',
    accumulatedPoints: 'Accumulated Points',
    activeRafflesTitle: 'Active Raffles',
    drawSoon: 'Coming soon',
    participateConfirmed: 'Entry confirmed! Good luck!',
    insufficientPoints: 'Not enough points!',
    insufficientPointsButton: 'Insufficient Points',
    noActiveRaffles: 'There are no active raffles at the moment.',
    howItWorks: 'How it works',
    raffleStepBuy: 'Buy',
    raffleStepBuyDesc: 'Every purchase in the store earns loyalty points according to the amount spent.',
    raffleStepAccumulate: 'Collect',
    raffleStepAccumulateDesc: 'Your points stay saved in your account.',
    raffleStepJoin: 'Join',
    raffleStepJoinDesc: 'Exchange your accumulated points for tickets.',
    yourTickets: 'Your Tickets',
    confirmed: 'Confirmed',
    noTicketsYet: 'You do not have tickets for active raffles yet.',
    accountTitle: 'My Account',
    alreadyCustomer: 'I am already a customer',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    login: 'Sign in',
    or: 'or',
    noAccountYet: "Don't have an account yet?",
    noAccountSubtitle: 'Create an account to shop faster, track your orders, and build your wishlist.',
    createAccount: 'Create Account',
    hello: 'Hello,',
    invalidLoginCredentials: 'Invalid email or password.',
    myOrders: 'My Orders',
    myAddresses: 'My Addresses',
    myData: 'My Data',
    logout: 'Sign out',
    loyaltyPointsBalance: 'You have {points} accumulated points.',
    viewRaffles: 'View Raffles',
    noOrdersYet: 'You do not have any orders yet',
    whatAboutNews: 'How about checking out our new arrivals?',
    seeProducts: 'See Products',
    primary: 'Primary',
    homeAddress: 'Home',
    edit: 'Edit',
    addAddress: 'Add Address',
    fullName: 'Full Name',
    cpf: 'Tax ID',
    cellphone: 'Mobile',
    phoneCountry: 'Phone Country',
    birthDate: 'Birth Date',
    birthDateInvalid: 'Enter a valid birth date in MM/DD/YYYY format.',
    gender: 'Gender',
    female: 'Female',
    male: 'Male',
    otherOrNoAnswer: 'Other / Prefer not to say',
    changePassword: 'Change Password',
    saveData: 'Save Data',
    addressModalTitle: 'Add Address',
    addressNickname: 'Address Name (e.g. Home, Work)',
    zipcode: 'Zip Code',
    street: 'Street',
    number: 'Number',
    complement: 'Complement',
    neighborhood: 'Neighborhood',
    city: 'City',
    state: 'State',
    saveAddress: 'Save Address',
    editMyData: 'Edit My Data',
    saveEdition: 'Save Changes',
    currentPassword: 'Current Password',
    yourCurrentPassword: 'Your current password',
    newPassword: 'New Password',
    minimumEightChars: 'At least 8 characters',
    confirmNewPassword: 'Confirm New Password',
    repeatNewPassword: 'Repeat the new password',
    updatePassword: 'Update Password',
    identification: 'Identification',
    identificationSubtitle: 'Sign in or create an account if you do not have one yet',
    accessData: 'Access Data',
    enterYourEmail: 'Enter your email',
    confirmEmail: 'Confirm email',
    emailConfirmationMismatch: 'The email confirmation does not match.',
    createPassword: 'Create a password',
    confirmPassword: 'Confirm password',
    passwordConfirmationMismatch: 'The password confirmation does not match.',
    accountAlreadyExists: 'An account with this email already exists.',
    accountCreationError: 'We could not finish the registration right now.',
    registrationType: 'Registration Type',
    individualPerson: 'Individual',
    legalEntity: 'Company',
    businessRegistrationUnavailable: 'Business registration is currently unavailable.',
    usOnlyRegistrationHint: 'Registration is currently available only for customers in the United States.',
    usOnlyShippingHint: 'Shipping is currently available only for addresses in the United States.',
    personalData: 'Personal Data',
    landline: 'Landline',
    corporateName: 'Legal Name',
    stateRegistration: 'State Registration',
    address: 'Address',
    country: 'Country',
    postalCode: 'Postal Code',
    stateProvince: 'State / Province / Region',
    dontKnowZipcode: "I don't know my zip code",
    addressFieldsLockedHint: 'Enter a valid zip code to unlock the address fields.',
    postalFieldsLockedHint: 'Enter a valid postal code to unlock the address fields.',
    addressManualCountryHint: 'Fill the address manually for this country.',
    zipcodeLookupLoading: 'Looking up the zip code...',
    zipcodeLookupSuccess: 'Zip code found. Complete the street number and any extra details.',
    zipcodeLookupNotFound: 'Zip code not found. Please fill the address manually.',
    zipcodeLookupError: 'We could not look up the zip code right now. Please fill the address manually.',
    postalLookupLoading: 'Looking up the postal code...',
    postalLookupSuccess: 'Postal code found. Review the data and complete the rest of the address.',
    postalLookupNotFound: 'Postal code not found. Please fill the address manually.',
    postalLookupError: 'We could not look up the postal code right now. Please fill the address manually.',
    reference: 'Reference',
    selectOption: 'Select',
    cancel: 'Cancel',
    checkoutConfirmed: 'Order Confirmed!',
    thanksForPurchase: 'Thank you for shopping at {store}.',
    orderNumberCopy: 'Your order number is {orderNumber}. We will send updates to your email.',
    backHome: 'Back to Home',
    checkoutStepIdentification: 'Identification',
    checkoutStepDelivery: 'Delivery',
    checkoutStepPayment: 'Payment',
    personalDataTitle: 'Personal Data',
    goToDelivery: 'Go to Delivery',
    deliveryAddressTitle: 'Delivery Address',
    avenue: 'Street / Avenue',
    shippingOptions: 'Shipping Options',
    shippingRatesLoading: 'Loading shipping options...',
    shippingRatesEstimated: 'Showing estimated shipping options. Connect a provider like Shippo for live carrier rates.',
    shippingRatesLive: 'Live carrier rates loaded.',
    shippingRatesError: 'We could not load shipping options right now.',
    shippingRatesEmpty: 'No shipping options are available for this destination.',
    shippingMethodRequired: 'Select a shipping option to continue.',
    shippingDeliveryWindow: 'Estimated delivery between {min} and {max} business days',
    shippingRefresh: 'Refresh shipping',
    businessDays7: 'Up to 7 business days',
    businessDays3: 'Up to 3 business days',
    back: 'Back',
    goToPayment: 'Go to Payment',
    paymentTitle: 'Payment',
    creditCard: 'Credit Card',
    stripeApplePay: 'Apple Pay',
    stripeGooglePay: 'Google Pay',
    stripeSecureCheckout: 'Secure Checkout',
    stripeCheckoutTitle: 'Complete your payment with Stripe',
    stripeCheckoutSubtitle: 'You will be redirected to a secure hosted checkout to finish your order safely.',
    stripeCheckoutDisabled: 'Stripe is not active in the admin panel yet. Add your keys to enable this flow.',
    stripeHostedCheckoutHint: 'Hosted Stripe Checkout with real-time payment validation.',
    stripeAvailableMethods: 'Available payment methods',
    stripeNoMethodEnabled: 'No Stripe payment method is enabled right now.',
    stripeProtectedPayment: 'Protected payment',
    stripeProtectedPaymentCopy: 'Sensitive payment details stay with Stripe and do not pass through the storefront.',
    stripeRewardsOnApproval: '{points} points released after payment approval',
    stripeContinueToCheckout: 'Continue to checkout',
    stripeRedirecting: 'Redirecting...',
    stripeCheckoutError: 'We could not start Stripe Checkout right now.',
    stripeVerificationError: 'We could not confirm the Stripe payment right now.',
    stripePaymentNotConfirmed: 'The payment has not been confirmed by Stripe yet.',
    stripeCheckoutProcessingTitle: 'Confirming your payment',
    stripeCheckoutProcessingSubtitle: 'We are validating your Stripe session and finishing your order.',
    stripeCheckoutReturnErrorTitle: 'We could not confirm the payment',
    paymentReturnToCart: 'Return to cart',
    cardNumber: 'Card Number',
    cardHolder: 'Cardholder Name',
    validity: 'Expiration (MM/YY)',
    installments: 'Installments',
    pixDiscount: 'PIX (5% Off)',
    completeOrder: 'Place Order',
    purchaseSummary: 'Purchase Summary',
    institutionalAbout: 'About the Brand',
    institutionalContact: 'Contact',
    institutionalTerms: 'Terms of Use',
    institutionalPrivacy: 'Privacy Policy',
    institutionalExchanges: 'Exchanges & Returns',
    institutionalFaq: 'Frequently Asked Questions',
    institutionalShipping: 'Shipping & Delivery',
  },
};

export function normalizeStorefrontLanguage(value?: string): StorefrontLanguage {
  return value === 'en-US' ? 'en-US' : 'pt-BR';
}

function interpolate(template: string, values?: Record<string, string | number>) {
  if (!values) return template;
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

export function useStorefront() {
  const { settings } = useSettings();
  const locale = normalizeStorefrontLanguage(settings.siteLanguage);

  useEffect(() => {
    document.documentElement.lang = locale;
  }, [locale]);

  const formattedPointsBase = useMemo(
    () => formatCurrencyValue(1, settings.storeCurrency, locale),
    [locale, settings.storeCurrency],
  );

  const formattedPointsRate = useMemo(
    () => new Intl.NumberFormat(locale).format(settings.pointsPerReal),
    [locale, settings.pointsPerReal],
  );

  const dictionary = useMemo(() => {
    const baseDictionary = storefrontTranslations[locale];
    const pointsSuffix = settings.pointsPerReal === 1 ? '' : 's';

    return {
      ...baseDictionary,
      rafflesHeroSubtitle:
        locale === 'pt-BR'
          ? `Cada ${formattedPointsBase} em compras gera ${formattedPointsRate} ponto${pointsSuffix}. Acumule e troque por bilhetes para nossos sorteios exclusivos.`
          : `Every ${formattedPointsBase} spent becomes ${formattedPointsRate} loyalty point${pointsSuffix}. Save up and exchange them for tickets in our exclusive raffles.`,
      raffleStepBuyDesc:
        locale === 'pt-BR'
          ? `Cada ${formattedPointsBase} gasto na loja equivale a ${formattedPointsRate} ponto${pointsSuffix} de lealdade.`
          : `Every ${formattedPointsBase} spent in the store equals ${formattedPointsRate} loyalty point${pointsSuffix}.`,
    };
  }, [formattedPointsBase, formattedPointsRate, locale, settings.pointsPerReal]);

  const t = useCallback(
    (key: string, values?: Record<string, string | number>) => interpolate(dictionary[key] || key, values),
    [dictionary],
  );

  const formatCurrency = useCallback(
    (value: number, currency = settings.storeCurrency) =>
      new Intl.NumberFormat(locale, {
        style: 'currency',
        currency,
      }).format(value),
    [locale, settings.storeCurrency],
  );

  const formatDate = useCallback(
    (value: string | Date) =>
      new Intl.DateTimeFormat(locale).format(typeof value === 'string' ? new Date(value) : value),
    [locale],
  );

  const formatNumber = useCallback(
    (value: number) => new Intl.NumberFormat(locale).format(value),
    [locale],
  );

  return useMemo(
    () => ({ locale, t, formatCurrency, formatDate, formatNumber }),
    [locale, t, formatCurrency, formatDate, formatNumber],
  );
}
